# Generated by Django 4.0.2 on 2022-03-21 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bugId', models.IntegerField(unique=True)),
                ('bugTitle', models.CharField(max_length=30, unique=True)),
                ('description', models.TextField(unique=True)),
                ('fixStatus', models.BooleanField(unique=True)),
            ],
        ),
    ]
