# Generated by Django 4.0.2 on 2022-03-21 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_bug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bug',
            old_name='bugId',
            new_name='bug_id',
        ),
        migrations.RenameField(
            model_name='bug',
            old_name='bugTitle',
            new_name='bug_title',
        ),
    ]
