# Generated by Django 4.0.2 on 2022-03-21 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_bugid_bug_bug_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bug',
            old_name='fixStatus',
            new_name='fix_status',
        ),
    ]
