# Generated by Django 4.0.2 on 2022-03-21 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_fixstatus_bug_fix_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='bug_title',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='bug',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='bug',
            name='fix_status',
            field=models.BooleanField(),
        ),
    ]
